listen: 127.0.0.1:8876
oidc:
- provider: google
  issuer: https://accounts.google.com
  clientID: ${OIDC_GOOGLE_CLIENT_ID}
  clientSecret: ${OIDC_GOOGLE_CLIENT_SECRET}
  redirect: ${OIDC_GOOGLE_REDIRECT}
  scopes:
    - profile
    - email
state:
  etcd:
    endpoints:
      - http://127.0.0.1:2379
    certFile: 
    keyFile:
    trustedCAFile: 
model:
  status:
    contentListLimit: 20
    contentLimit: 380
