listen: 127.0.0.1:8876
oidc:
- provider: google
  issuer: https://accounts.google.com
  clientID: ${OIDC_GOOGLE_CLIENT_ID}
  clientSecret: ${OIDC_GOOGLE_CLIENT_SECRET}
  redirect: ${OIDC_GOOGLE_REDIRECT}
  scopes:
    - profile
    - email
- provider: github
  authURL: https://github.com/login/oauth/authorize
  tokenURL: https://github.com/login/oauth/access_token
  userInfoURL: https://api.github.com/user
  clientID: ${OIDC_GITHUB_CLIENT_ID}
  clientSecret: ${OIDC_GITHUB_CLIENT_SECRET}
  redirect: ${OIDC_GITHUB_REDIRECT}
  trustEmail: true
  userMeta:
    picture: avatar_url
  scopes:
    - read:user
    - user:email
state:
  etcd:
    endpoints:
      - http://127.0.0.1:2379
    certFile: 
    keyFile:
    trustedCAFile: 
storage:
  s3:
    accessKeyID: xxx
    secretAccessKey: xxx
    endpoint: cos.ap-guangzhou.myqcloud.com
    region: ap-guangzhou
    bucket: xxx
model:
  status:
    contentListLimit: 20
    contentLimit: 4096
    overviewLimit: 256
  media:
    countPerDayLimit: 20
admins:
  - 2u4buCaWFhJg214tm
